## Application
#spring.application.name=Malaysia Rainfall System
#
## MySQL Database
## Buang tanda '' pada username dan password
#spring.datasource.url=jdbc:mysql://localhost:3306/rainfall_db?useSSL=false&serverTimezone=Asia/Kuala_Lumpur&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA/Hibernate
## Gunakan 'update' supaya table auto-create/fix
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#
## Logging (Optional tapi bagus untuk debug)
#logging.level.com.amar.rainfall=DEBUG

spring.application.name=Selangor Rainfall

# Jika XAMPP ada, dia guna MySQL. Jika tak ada, dia guna H2 (RAM)
spring.datasource.url=jdbc:mysql://localhost:3306/rainfall_db?useSSL=false&serverTimezone=Asia/Kuala_Lumpur
spring.datasource.username=root
spring.datasource.password=

# Toleransi jika MySQL tiada (Jangan bagi app crash)
spring.datasource.continue-on-error=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect